name: Code check

on:
  pull_request:
    branches: ["*"]

env:
  NEXT_PUBLIC_APP_URL: "https://fake.com"
  DATABASE_URL: "fake"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "fake"
  CLERK_SECRET_KEY: "fake"
  RESEND_API_KEY: "fake"
  EMAIL_FROM_ADDRESS: "fake@fake.com"
  UPLOADTHING_SECRET: "fake"
  UPLOADTHING_APP_ID: "fake"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "fake"
  STRIPE_API_KEY: "fake"
  STRIPE_WEBHOOK_SECRET: "fake"
  STRIPE_STD_MONTHLY_PRICE_ID: "fake"
  STRIPE_PRO_MONTHLY_PRICE_ID: "fake"

jobs:
  typecheck-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      # TODO: Linting is failing because of contentlayer types, need to fix that
      # - name: Run lint
      #   run: bun run lint

      - name: Run typecheck
        run: bun run typecheck
