name: Code check

on:
  pull_request:
    branches: ["*"]

env:
  NEXT_PUBLIC_APP_URL: "fake"
  DATABASE_URL: "fake"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "fake"
  CLERK_SECRET_KEY: "fake"
  RESEND_API_KEY: "fake"
  EMAIL_FROM_ADDRESS: "fake"
  UPLOADTHING_SECRET: "fake"
  UPLOADTHING_APP_ID: "fake"
  STRIPE_API_KEY: "fake"
  STRIPE_WEBHOOK_SECRET: "fake"
  STRIPE_PRO_STORE_PRICE_ID: "fake"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: pnpm lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR

  tsc:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: pnpm typecheck
